services:
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommercedb
    volumes:
      - ecommerce-app-data:/var/lib/postgresql/data
    networks:
      - ecommerce-app-nw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  e-commerce-app:
    image: rosaflores/e-commerce-backend:latest
    container_name: e-commerce-app
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres-db
      - DB_NAME=ecommercedb
      - DB_PASSWORD=password
      - DB_PORT=5432
    networks:
      - ecommerce-app-nw
    ports:
      - "3030:5000"  # Asegúrate de que el puerto sea el correcto
    command: npm run dev
    depends_on:
      postgres_db:
        condition: service_healthy

  e-commerce-frontend:  # Cambiado a un nombre más coherente
    build:
      context: ./  # Asegúrate que esta ruta sea correcta
      dockerfile: Dockerfile
    container_name: e-commerce-frontend
    networks:
      - ecommerce-app-nw
    ports:
      - "80:80"
    depends_on:
      - e-commerce-app
    volumes:
     
      - ./src:/app/src  # Monta el código fuente de tu frontend en el contenedor
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf  # Configuración de NGINX
      - /app/node_modules  # Evita conflictos de dependencias

networks:
  ecommerce-app-nw:
    driver: bridge

volumes:
  ecommerce-app-data: